### ISSUE TITLE
HTTP Error 400

### ISSUE THREAD

**Issue by SknerusMcK** [A4kon/BOT_ZSE#3]
Nie wiem, czy to wina moja, kodu czy VULCANA, ale wywala mi error 400:
```
Odświeżam Godzina: 2020-3-27 9:33:15
(node:10244) UnhandledPromiseRejectionWarning: HTTPError: Response code 400 (Bad Request)
    at EventEmitter.emitter.on (/home/sknerus/BOT_ZSE/node_modules/got/source/as-promise.js:74:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:10244) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:10244) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by SknerusMcK** [comment]
Zamykam, użyłem https://github.com/kapi2289/vulcan-api :grinning:
